import '../models/trip_model.dart';

class TripService {
  Future<List<Trip>> getTopJourneys() async {
    await Future.delayed(const Duration(milliseconds: 800));
    return [
      Trip(
        id: '1',
        title: 'Da Nang - Ba Na - Hoi An',
        image: 'assets/images/danang_pool.png',
        location: 'Da Nang, Vietnam',
        date: 'Jan 30, 2020',
        time: '9:00 AM',
        duration: '3 days',
        price: r'$400.00',
        guide: 'Tuan Tran',
        guideAvatar: 'assets/images/Guide Modal.png',
        rating: 5,
        likes: '1247 likes',
        isSaved: true,
      ),
      Trip(
        id: '2',
        title: 'Thailand Island Hopping',
        image: 'assets/images/thailand.png',
        location: 'Phuket, Thailand',
        date: 'Feb 15, 2020',
        time: '10:00 AM',
        duration: '5 days',
        price: r'$600.00',
        guide: 'Somsak',
        guideAvatar: 'assets/images/Mask Group copy 4.png',
        rating: 5,
        likes: '856 likes',
      ),
      Trip(
        id: '3',
        title: 'Hanoi Cultural Heritage',
        image: 'assets/images/ho_guom.png',
        location: 'Hanoi, Vietnam',
        date: 'Mar 10, 2020',
        time: '08:30 AM',
        duration: '2 days',
        price: r'$150.00',
        guide: 'Emmy',
        guideAvatar: 'assets/images/Guide Modal (1).png',
        rating: 4,
        likes: '231 likes',
      ),
      Trip(
        id: '4',
        title: 'Ha Long Bay Cruise',
        image: 'assets/images/hanoi_bay.png',
        location: 'Ha Long, Vietnam',
        date: 'Mar 20, 2020',
        time: '09:00 AM',
        duration: '2 days',
        price: r'$250.00',
        guide: 'Minh Anh',
        guideAvatar: 'assets/images/Mask Group copy.png',
        rating: 5,
        likes: '1542 likes',
      ),
      Trip(
        id: '5',
        title: 'Ho Chi Minh City Tour',
        image: 'assets/images/duc_ba_church.png',
        location: 'Ho Chi Minh, Vietnam',
        date: 'Apr 05, 2020',
        time: '08:00 AM',
        duration: '1 day',
        price: r'$50.00',
        guide: 'Khai Ho',
        guideAvatar: 'assets/images/Guide Modal (3).png',
        rating: 4,
        likes: '412 likes',
      ),
      Trip(
        id: '6',
        title: 'Seoul Modern & Ancient',
        image: 'assets/images/Mask Group (3).png',
        location: 'Seoul, South Korea',
        date: 'Apr 15, 2020',
        time: '10:00 AM',
        duration: '4 days',
        price: r'$800.00',
        guide: 'Yoo Jin',
        guideAvatar: 'assets/images/Mask Group (3).png',
        rating: 5,
        likes: '2103 likes',
      ),
      Trip(
        id: '7',
        title: 'Sydney Opera & Bridge',
        image: 'assets/images/Mask Group (2).png',
        location: 'Sydney, Australia',
        date: 'May 01, 2020',
        time: '09:00 AM',
        duration: '3 days',
        price: r'$550.00',
        guide: 'John Smith',
        guideAvatar: 'assets/images/Mask Group (2).png',
        rating: 5,
        likes: '678 likes',
      ),
      Trip(
        id: '8',
        title: 'Paris Romantic Escape',
        image: 'assets/images/Mask Group (1).png',
        location: 'Paris, France',
        date: 'May 10, 2020',
        time: '10:00 AM',
        duration: '3 days',
        price: r'$900.00',
        guide: 'Elena',
        guideAvatar: 'assets/images/Mask Group (1).png',
        rating: 5,
        likes: '3421 likes',
      ),
      Trip(
        id: '9',
        title: 'Tokyo Food & Lights',
        image: 'assets/images/Mask Group copy 2.png',
        location: 'Tokyo, Japan',
        date: 'May 20, 2020',
        time: '18:00 PM',
        duration: '2 days',
        price: r'$450.00',
        guide: 'Aiko',
        guideAvatar: 'assets/images/Mask Group copy 2.png',
        rating: 5,
        likes: '1890 likes',
      ),
      Trip(
        id: '10',
        title: 'Hue Imperial City',
        image: 'assets/images/hcm_mausoleum.png',
        location: 'Hue, Vietnam',
        date: 'Jun 01, 2020',
        time: '08:00 AM',
        duration: '1 day',
        price: r'$60.00',
        guide: 'Minh Anh',
        guideAvatar: 'assets/images/Mask Group copy.png',
        rating: 4,
        likes: '156 likes',
      ),
    ];
  }

  Future<List<Trip>> getMyTrips() async {
    await Future.delayed(const Duration(milliseconds: 800));
    return [
      Trip(
        id: '101',
        title: 'Dragon Bridge Trip',
        image: 'assets/images/danang_bridge.png',
        location: 'Da Nang, Vietnam',
        date: 'Jan 30, 2020',
        time: '13:00 - 15:00',
        price: r'$20.00',
        guide: 'Tuan Tran',
        guideAvatar: 'assets/images/Mask Group copy.png',
        attractions: ['Dragon Bridge', 'Love Bridge', 'Han River'],
        status: '', // Current Trip
      ),
      Trip(
        id: '102',
        title: 'Ho Guom Trip',
        image: 'assets/images/ho_guom.png',
        location: 'Hanoi, Vietnam',
        date: 'Feb 2, 2020',
        time: '8:00 - 10:00',
        price: r'$20.00',
        guide: 'Emmy',
        guideAvatar: 'assets/images/Mask Group (1).png',
        status: 'Confirmed', // Next Trip
      ),
      Trip(
        id: '103',
        title: 'Bana Hills Tour',
        image: 'assets/images/danang_pool.png',
        location: 'Da Nang, Vietnam',
        date: 'Jan 15, 2020',
        time: '08:00 - 17:00',
        price: r'$50.00',
        guide: 'Linh Hana',
        guideAvatar: 'assets/images/Guide Modal (2).png',
        isFinished: true, // Past Trip
      ),
      Trip(
        id: '104',
        title: 'Melbourne - Sydney',
        image: 'assets/images/duc_ba_church.png',
        location: 'Australia',
        date: 'Jan 30, 2020',
        time: '10:00 AM',
        duration: '3 days',
        price: r'$600.00',
        guide: 'John Smith',
        guideAvatar: 'assets/images/Mask Group (2).png',
        isSaved: true, // Wish List
        rating: 5,
        likes: '1247 likes',
      ),
      Trip(
        id: '105',
        title: 'Paris Sightseeing',
        image: 'assets/images/Mask Group (1).png',
        location: 'Paris, France',
        date: 'Mar 15, 2020',
        time: '09:00 AM',
        price: r'$100.00',
        guide: 'Elena',
        guideAvatar: 'assets/images/Mask Group (1).png',
        status: 'Pending',
      ),
      Trip(
        id: '106',
        title: 'Tokyo Night Market',
        image: 'assets/images/Mask Group copy 2.png',
        location: 'Tokyo, Japan',
        date: 'Mar 20, 2020',
        time: '19:00 PM',
        price: r'$80.00',
        guide: 'Aiko',
        guideAvatar: 'assets/images/Mask Group copy 2.png',
        isSaved: true,
      ),
      Trip(
        id: '107',
        title: 'Seoul Food Tour',
        image: 'assets/images/Mask Group (3).png',
        location: 'Seoul, Korea',
        date: 'Apr 01, 2020',
        time: '11:00 AM',
        price: r'$120.00',
        guide: 'Yoo Jin',
        guideAvatar: 'assets/images/Mask Group (3).png',
        status: 'Confirmed',
      ),
      Trip(
        id: '108',
        title: 'Bangkok Street Food',
        image: 'assets/images/thailand.png',
        location: 'Bangkok, Thailand',
        date: 'Apr 10, 2020',
        time: '18:00 PM',
        price: r'$40.00',
        guide: 'Somsak',
        guideAvatar: 'assets/images/Mask Group copy 4.png',
        isFinished: true,
      ),
      Trip(
        id: '109',
        title: 'Hue Citadel Walk',
        image: 'assets/images/hcm_mausoleum.png',
        location: 'Hue, Vietnam',
        date: 'May 05, 2020',
        time: '08:00 AM',
        price: r'$30.00',
        guide: 'Minh Anh',
        guideAvatar: 'assets/images/Mask Group copy.png',
        isSaved: true,
      ),
      Trip(
        id: '110',
        title: 'Ha Long Bay One Day',
        image: 'assets/images/hanoi_bay.png',
        location: 'Ha Long, Vietnam',
        date: 'May 15, 2020',
        time: '07:00 AM',
        price: r'$90.00',
        guide: 'Minh Anh',
        guideAvatar: 'assets/images/Mask Group copy.png',
        status: 'Confirmed',
      ),
    ];
  }

  Future<bool> bookTrip(String tripId) async {
    await Future.delayed(const Duration(seconds: 1));
    return true;
  }

  Future<List<Trip>> getFeaturedTours() async {
    await Future.delayed(const Duration(milliseconds: 900));
    return [
      Trip(
        id: 'f1',
        title: 'Da Nang - Ba Na - Hoi An',
        image: 'assets/images/danang_pool.png',
        location: 'Da Nang, Vietnam',
        date: 'Jan 30, 2020',
        time: '9:00 AM',
        duration: '3 days',
        price: r'$400.00',
        guide: 'Tuan Tran',
        guideAvatar: 'assets/images/Guide Modal.png',
        likes: '1247 likes',
      ),
      Trip(
        id: 'f2',
        title: 'Melbourne - Sydney',
        image: 'assets/images/duc_ba_church.png',
        location: 'Australia',
        date: 'Jan 30, 2020',
        time: '10:00 AM',
        duration: '3 days',
        price: r'$600.00',
        guide: 'John Smith',
        guideAvatar: 'assets/images/Mask Group (2).png',
        isSaved: true,
        likes: '1247 likes',
      ),
    ];
  }

  Future<List<Map<String, dynamic>>> getTopExperiences() async {
    await Future.delayed(const Duration(milliseconds: 700));
    return [
      {
        'image': 'assets/images/Mask Group (1).png',
        'guideImage': 'assets/images/Guide Modal.png',
        'guideName': 'Tuan Tran',
        'title': '2 Hour Bicycle Tour exploring Hoian',
        'location': 'Hoian, Vietnam',
      },
      {
        'image': 'assets/images/Group 111.png',
        'guideImage': 'assets/images/Guide Modal (2).png',
        'guideName': 'Linh Hana',
        'title': '1 day at Bana Hill',
        'location': 'Bana, Vietnam',
      },
    ];
  }
}
